#%RAML 0.8
title: WWST Stateless Power Toggle Button
version: v1.0.0-20180823
documentation:
- title: Copyright (c) 2018 Samsung Electronics Co., Ltd. All rights reserved.
  	       Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

	      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
- Button: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.statelessPowerToggleButton.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017, 2018 SmartThings. All rights reserved.",
      "title": "WWST Stateless Power Toggle Button",
      "definitions": {
        "x.com.st.statelessPowerToggleButton": {
          "type": "object",
          "properties": {
            "availableButtons": {
              "type": "array",
              "readOnly": true,
              "description": "Array of possible buttons the device supports.",
              "items": {
                "type": "string",
                "enum": ["powerToggle"]
              }
            },
            "button": {
              "description": "Desired button",
              "type": "string",              
              "enum": ["powerToggle"]
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.statelessPowerToggleButton"
        }
      ],
      "required": [
        "availableButtons"
      ]
    }
- ButtonUpdate: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.statelessPowerToggleButton.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017, 2018 SmartThings. All rights reserved.",
      "title": "WWST Stateless Power Toggle Button Update",
      "definitions": {
        "x.com.st.statelessPowerToggleButton": {
          "type": "object",
          "properties": {
            "button": {
              "description": "Desired command",
              "type": "string",              
              "enum": ["powerToggle"]
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.statelessPowerToggleButton"
        }
      ],
      "required": [
        "button"
      ]
    }

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.s","oic.if.baseline"]

/WWSTPlayermodesResURI:
  description: |
        Stateless Power Toggle Button
  displayName: WWST Stateless Power Toggle Button
  is: [ interface ]

  get:
    description: |
      Retrieves the current Stateless Power Toggle Button
    responses:
      200:
        body:
          application/json:
            schema: Button
            example: |
              {
                "rt":             ["x.com.st.statelessPowerToggleButton"],
                "id":             "unique_example_id",
                "availableButtons": [ "powerToggle" ],
                "button": "powerToggle"
              }

  post:
    description: |
      Sets the desired Stateless Power Toggle Button
    body:
      application/json:
        schema: ButtonUpdate
        example: |
          {
            "id":    "unique_example_id",
            "button": "powerToggle"
          }
    responses:
      200:
        body:
          application/json:
            schema: ButtonUpdate
            example: |
              {
                "id":    "unique_example_id",
                "button": "powerToggle"
              }
      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for button that is not found in availableButtons.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: Button
            example: |
              {
                "id":             "unique_example_id",
                "availableButtons": [],
                "button": "powerToggle"
              }