#%RAML 0.8
title: WWST Language Setting
version: v1.0.0-20180928
documentation:
  - title: Copyright (c) 2018 Samsung Electronics Co., Ltd. All rights reserved.
  	       Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

	      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
schemas:
- Language: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.languageSetting.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017, 2018 SmartThings. All rights reserved.",
      "title": "WWST Language Setting",
      "definitions": {
        "x.com.st.languageSetting": {
          "type": "object",
          "properties": {
            "supportedLanguages": {
              "type": "array",
              "readOnly": true,
              "description": "Languages supported by the device",
              "items": {
                "type": "string"
              }
            },
            "language": {
              "description": "The current language of the device",
              "type": "string"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.languageSetting"
        }
      ],
      "required": [
        "supportedLanguages"
      ]
    }
- LanguageUpdate: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.languageSetting.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description": "Copyright (c) 2016, 2017, 2018 SmartThings. All rights reserved.",
      "title": "WWST Language Setting Update",
      "definitions": {
        "x.com.st.languageSetting": {
          "type": "object",
          "properties": {
            "language": {
              "description": "The current language of the device",
              "type": "string"
            }
          }
        }
      },
      "type": "object",
      "allOf": [
        {
          "$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"
        },
        {
          "$ref": "#/definitions/x.com.st.languageSetting"
        }
      ],
      "required": [
        "language"
      ]
    }

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.a","oic.if.s","oic.if.baseline"]

/WWSTLanguageSettingResURI:
  description: |
        Language Setting
  displayName: WWST Language Setting
  is: [ interface ]

  get:
    description: |
      Retrieves the current language setting
    responses:
      200:
        body:
          application/json:
            schema: Language
            example: |
              {
                "rt":             ["x.com.st.languageSetting"],
                "id":             "unique_example_id",
                "supportedLanguages": [ "en", "ko" ],
                "language": "en"
              }

  post:
    description: |
      Sets the desired language setting
    body:
      application/json:
        schema: LanguageUpdate
        example: |
          {
            "id":    "unique_example_id",
            "language": "ko"
          }
    responses:
      200:
        body:
          application/json:
            schema: LanguageUpdate
            example: |
              {
                "id":    "unique_example_id",
                "language": "ko"
              }
      403:
        description: |
          This response is generated by the OIC Server when the client sends:
            An update with an value for language that is not found in supportedLanguages.
          The server responds with the current resource representation.
        body:
          application/json:
            schema: Language
            example: |
              {
                "id":             "unique_example_id",
                "supportedLanguages": ["en"],
                "language": "ko"
              }