#%RAML 0.8
title: STConsumable
version: v1.0.0-20180827
documentation:
  - title: Copyright (c) 2018 Samsung Electronics Co., Ltd. All rights reserved.
  	       Copyright (c) 2016 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

	      THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
schemas:
- Consumable: |
    {
      "id": "http://www.samsung.com/schemas/x.com.st.consumable.json#",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "description" : "Copyright (c) 2016, 2017, 2018 SmartThings. All rights reserved.",
      "title": "STConsumable",
      "definitions": {
        "x.com.st.consumable": {
            "properties": {
              "consumableStatus": {
                "type": "string",
                "enum": ["good", "maintenance_required", "missing", "order", "replace"],
                "description": "Status of the consumable"
              }
            }
        }
      },
      "type": "object",
      "allOf": [
        {"$ref": "oic.core.json#/definitions/oic.core"},
        {"$ref": "oic.baseResource.json#/definitions/oic.r.baseresource"},
        {"$ref": "#/definitions/x.com.st.consumable"}
      ],
      "required": ["consumable"]
    }
traits:
 - interface :
     queryParameters:
       if:
         enum: ["oic.if.baseline", "oic.if.s", "oic.if.a"]

/consumable:
  displayName: Consumable
  description: |
    This resource implements consumable capability from SmartThings.

  is : ['interface']

  get:
    description: |
      Retrieves the replaceable components for the device

    responses :
      200:
        body:
          application/json:
            schema: Consumable
            example: |
              {
                "id": "unique_example_id",
                "consumable": "good"
              }
  post:
    description: |
      Set the consumable status

    body:
      application/json:
        schema: Consumable

    responses :
      200:
        body:
          application/json:
            schema: Consumable
            example: |
              {
                "id":  "unique_example_id",
                "consumable":  "order"
              }
